# Generated by Django 3.1.7 on 2021-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koleksi_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekaman',
            name='juz',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
