# Generated by Django 3.1.7 on 2021-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CariAyatDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, default='', max_length=1000)),
                ('prediction', models.CharField(blank=True, default='', max_length=1000)),
                ('list_nama_surat', models.CharField(blank=True, default='', max_length=1000)),
                ('arti', models.CharField(blank=True, default='', max_length=1000)),
                ('segment', models.CharField(blank=True, default='cari', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('remark', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
